name: Publish to Modrinth

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Modrinth configuration
          modrinth-id: ${{ secrets.MODRINTH_PROJECT_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          
          # GitHub Release configuration
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Files to upload
          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
          
          # Mod information
          name: IsTyping
          version-type: release
          loaders: fabric
          
          # Game versions
          game-versions: |
            1.20.1
          
          # Dependencies
          dependencies: |
            fabric-api(required){modrinth:P7dR8mSH}
            architectury-api(required){modrinth:lhGA9TYQ}
          
          # Java version
          java: 21
          
          # Retry configuration
          retry-attempts: 3
          retry-delay: 10000